name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag container-test:$(date +%s)
      if: success()
    - name: Run Trivy
      run: |
         docker pull aquasec/trivy:latest
         docker run --rm -v $(pwd):/workdir -w /workdir aquasec/trivy:latest your-docker-image-name:latest
      if: success()
         
